[package]
name = "iof"
version = "0.1.5"
edition = "2021"
description = "Read and write data from console or file in specified formats."
keywords = ["input", "oj", "stream", "formatted"]
categories = [
    "value-formatting",
    "command-line-interface",
    "mathematics",
    "data-structures",
]
readme = "README.md"
rust-version = "1.63"
repository = "https://github.com/TheVeryDarkness/iof"
license = "MIT OR Apache-2.0"

[dependencies]

[features]
# default = ["auto_unwrap"]
# auto_unwrap = []

[dev-dependencies]
anyhow = "1.0.86"
rayon = "1.10.0"
