[package]
name = "iof"
version = "0.1.0"
edition = "2021"
description = "Read and write data from console or file in specified formats."

[dependencies]

[features]
# default = ["auto_unwrap"]
auto_unwrap = []

[dev-dependencies]
anyhow = "1.0.86"
