[package]
name = "iof"
version = "0.1.1"
edition = "2021"
description = "Read and write data from console or file in specified formats."
rust-version = "1.63"
repository = "https://github.com/TheVeryDarkness/iof"
license = "MIT OR Apache-2.0"

[dependencies]

[features]
# default = ["auto_unwrap"]
# auto_unwrap = []

[dev-dependencies]
anyhow = "1.0.86"
