max_width = 100

imports_granularity = "Crate"
group_imports = "One"

# error_on_line_overflow = true
# error_on_unformatted = true

# reorder_impl_items = true

# format_code_in_doc_comments = true
format_macro_matchers = true

use_field_init_shorthand = true
