name: Criterion.rs with Benchmark Action
on: [push]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Criterion.rs benchmark example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "nightly"
      - name: Prepare for benchmark
        run: cargo run --example benchmark_integers
      - name: Run benchmark
        run: cargo bench | tee output.json
      - name: Store benchmark result - separate results repo
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Criterion.rs Benchmark
          tool: "cargo"
          output-file-path: output.json
          github-token: ${{ secrets.BENCHMARK_ACTION_BOT_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "200%"
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: "@TheVeryDarkness"
          gh-repository: "github.com/TheVeryDarkness/iof-benchmark-results"
