name: Criterion.rs with Benchmark Action
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Criterion.rs benchmark example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Rust Toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "nightly"
      - name: Prepare for benchmark
        run: cargo run --example benchmark_integers
      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project iof \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --err \
          --adapter criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "cargo bench"
